# Generated by Django 6.0 on 2026-01-07 08:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_follows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='follows',
            field=models.ManyToManyField(limit_choices_to={'role': 'CREATOR'}, null=True, to=settings.AUTH_USER_MODEL, verbose_name='suit'),
        ),
    ]
