# Generated by Django 6.0 on 2026-01-08 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('litrevu', '0005_alter_review_user_alter_userfollows_followed_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfollows',
            options={'verbose_name_plural': 'users followed'},
        ),
    ]
